# Generated by Django 4.0.3 on 2022-03-28 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommuser',
            name='credit_card',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Credit card number doesnt comply', regex='^[456](?!([0-9]\\1{4,})(?:[0-9]{16})')]),
        ),
    ]
